version: "3"
services:
  chrome:
    image: selenium/node-chrome:latest
    tty: false
    stdin_open: false
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

 

  selenium-hub:
    image: selenium/hub:latest
    tty: false
    stdin_open: false
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  automation:
    image: automation-test:latest
    container_name: automationtest
    build: .
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - HOST_NAME=selenium-hub
    volumes:
      - ./src/test/java/report:/app/src/test/java/report


